/// DAX Measures for CMS Quality Scorecard
table _Measures
	lineageTag: 99999999-aaaa-bbbb-cccc-999999999999

	measure 'Quality Rate' =
		DIVIDE(
			CALCULATE(COUNTROWS(agg_quality_measures), agg_quality_measures[quality_met] = TRUE()),
			CALCULATE(COUNTROWS(agg_quality_measures), agg_quality_measures[in_denominator] = TRUE()),
			0
		)
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999991

	measure 'Measures Met' =
		COUNTROWS(
			FILTER(
				VALUES(agg_quality_summary[measure_id]),
				CALCULATE(MAX(agg_quality_summary[quality_rate])) >= CALCULATE(MAX(agg_quality_summary[benchmark_rate]))
			)
		)
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999992

	measure 'Total Measures' =
		DISTINCTCOUNT(agg_quality_summary[measure_id])
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999993

	measure 'Patients Measured' =
		DISTINCTCOUNT(agg_quality_measures[patient_id])
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999994

	measure 'Open Care Gaps' =
		CALCULATE(COUNTROWS(care_gaps), care_gaps[gap_status] = "open")
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999995

	measure 'Total Billed' =
		SUMX(fact_claim, fact_claim[billed_amount])
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999996

	measure 'Total Paid' =
		SUMX(fact_claim, fact_claim[paid_amount])
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999997

	measure 'Collection Rate' =
		DIVIDE(SUMX(fact_claim, fact_claim[paid_amount]), SUMX(fact_claim, fact_claim[billed_amount]), 0)
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999998

	measure 'Denial Rate' =
		DIVIDE(
			CALCULATE(COUNTROWS(fact_claim), fact_claim[denial_flag] = 1),
			COUNTROWS(fact_claim),
			0
		)
		lineageTag: 99999999-aaaa-bbbb-cccc-999999999999

	measure 'Avg PDC Score' =
		AVERAGE(agg_medication_adherence[pdc_score])
		lineageTag: 99999999-aaaa-bbbb-cccc-99999999999a

	measure 'Non-Adherent Patients' =
		CALCULATE(COUNTROWS(agg_medication_adherence), agg_medication_adherence[adherence_category] = "Non-Adherent")
		lineageTag: 99999999-aaaa-bbbb-cccc-99999999999b

	measure 'Avg Claim Amount' =
		AVERAGE(fact_claim[billed_amount])
		lineageTag: 99999999-aaaa-bbbb-cccc-99999999999c

	measure 'Revenue Leakage' =
		SUM(fact_claim[billed_amount]) - SUM(fact_claim[paid_amount])
		lineageTag: 99999999-aaaa-bbbb-cccc-99999999999d

	measure 'Total Claims' =
		COUNTROWS(fact_claim)
		lineageTag: 99999999-aaaa-bbbb-cccc-99999999999e

	measure 'Quality Rate (Medicare)' =
		CALCULATE([Quality Rate], agg_quality_measures[payer_category] = "Medicare")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a1

	measure 'Quality Rate (Medicaid)' =
		CALCULATE([Quality Rate], agg_quality_measures[payer_category] = "Medicaid")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a2

	measure 'Quality Rate (Commercial)' =
		CALCULATE([Quality Rate], agg_quality_measures[payer_category] = "Commercial")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a3

	measure 'Quality Rate (Uninsured)' =
		CALCULATE([Quality Rate], agg_quality_measures[payer_category] = "Uninsured")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a4

	measure 'Collection Rate (Medicare)' =
		CALCULATE([Collection Rate], fact_claim[payer_category] = "Medicare")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a5

	measure 'Collection Rate (Medicaid)' =
		CALCULATE([Collection Rate], fact_claim[payer_category] = "Medicaid")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a6

	measure 'Collection Rate (Commercial)' =
		CALCULATE([Collection Rate], fact_claim[payer_category] = "Commercial")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a7

	measure 'Denial Rate (Medicare)' =
		CALCULATE([Denial Rate], fact_claim[payer_category] = "Medicare")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a8

	measure 'Denial Rate (Medicaid)' =
		CALCULATE([Denial Rate], fact_claim[payer_category] = "Medicaid")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999a9

	measure 'Denial Rate (Commercial)' =
		CALCULATE([Denial Rate], fact_claim[payer_category] = "Commercial")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999aa

	measure 'Total Paid (Medicare)' =
		CALCULATE(SUM(fact_claim[paid_amount]), fact_claim[payer_category] = "Medicare")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999ab

	measure 'Total Paid (Medicaid)' =
		CALCULATE(SUM(fact_claim[paid_amount]), fact_claim[payer_category] = "Medicaid")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999ac

	measure 'Total Paid (Commercial)' =
		CALCULATE(SUM(fact_claim[paid_amount]), fact_claim[payer_category] = "Commercial")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999ad

	measure 'Patients Measured (Medicare)' =
		CALCULATE([Patients Measured], agg_quality_measures[payer_category] = "Medicare")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999ae

	measure 'Patients Measured (Medicaid)' =
		CALCULATE([Patients Measured], agg_quality_measures[payer_category] = "Medicaid")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999af

	measure 'Patients Measured (Commercial)' =
		CALCULATE([Patients Measured], agg_quality_measures[payer_category] = "Commercial")
		lineageTag: 99999999-aaaa-bbbb-cccc-9999999999b0